### ISSUE TITLE
[BPMN] Atualizar planilha de acordo com o CMMI v3

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2#10]

**Comment by brilacerda** [comment]
Eu fiz isso na hora que ele falou na aula.

**Comment by JoaoGFarias** [comment]
@brilacerda 
Gabriela, atualiza  o repositório com a versão atualizada e fecha essa issue, por favor.
