### ISSUE TITLE
[BPMN] Brainstorm de processos a serem cobertos

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2#12]
Criar um mapa-mental com os processos a serem documentados, seus principais atores, inputs, outputs e descrição de alto-nível do contexto.

Watchers:

@JoaoGFarias
@brunnorbc 
@vsychen 
@acff

**Comment by brilacerda** [comment]
Eu até que tentei, mas tem que ler aquele capítulo msm...
