### ISSUE TITLE
[Artigo] Criar do TMM

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2#13]
Criar um documento markdown com um resumo dos principais pontos do [TMM](http://static1.1.sqspcdn.com/static/f/702523/9173311/1288308903013/199811-Burnstein.pdf?token=wcUib27eXLMjDjQWmer1333RWoI%3Dhttps://en.wikipedia.org/wiki/Testing_Maturity_Model), de modo que possamos entender o estado de avaliação tradicional de maturidade de testes. 

@vsychen, podes me ajudar com isso?

**Comment by JoaoGFarias** [comment]
Pergunta aberta: Existem outros frameworks tradicionais concorrentes ao TMM?

**Comment by brilacerda** [comment]
O que é TMM? :|

**Comment by JoaoGFarias** [comment]
[Testing Maturity Level](https://en.wikipedia.org/wiki/Testing_Maturity_Model).
Referências na issue atualizadas com esse link.

**Comment by vsychen** [comment]
Posso, mas precisa ser depois de terça, q segunda e terça tenho (mini)prova.
Sobre outros frameworks, acho que TPI e TIM são, mas ainda não dei uma lida nesse assunto. Esses dois foram apresentados pelo grupo do ISO25000, mas só por cima.

**Comment by JoaoGFarias** [comment]
@vsychen eu já tenho  material sobre TMM, por isso me assinalei nesta issue.
Criar duas issues para o TPI e TIM para trackearmos o estudo desses frameworks - e se tu quiser fazer, se assinala nelas.

Para quem não viu, eu compartilhei no facebook uma lista não-acurada sobre o artigo. [Dêem uma olhada](https://www.evernote.com/l/ASx86-DOYadDm6Upk9yYT6TuPpZnw11A1cs) e se tiver algo interessante, criem issues para trackearmos o assunto.

**Comment by JoaoGFarias** [comment]
@vsychen Podes passar algum link sobre TPI e TIM

**Comment by vsychen** [comment]
@JoaoGFarias ainda não li nada sobre, mas achei uns links aqui
Dentre esses 3, eu dei uma olhada rápida, o 3º link fala um pouco sobre TPI e TIM também, além de ter uma seção de comparação entre TPI/TMM e TIM/TMM
TPI
[Andersin.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/286410/Andersin.pdf)
TIM
[a891451d001f9f6fdd2b9b4f896da567f0ab.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/286414/a891451d001f9f6fdd2b9b4f896da567f0ab.pdf)
Comparação entre TMM, TPI e TIM
[12-4-1-FPdef.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/286411/12-4-1-FPdef.pdf)

**Comment by JoaoGFarias** [comment]
WIP aqui: https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/blob/master/artigo/tmmi/tmmi.md

**Comment by JoaoGFarias** [comment]
[Aguardando revisão](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/blob/master/artigo/tmmi/tmmi.md)
