### ISSUE TITLE
[Artigo] Criar resumo do TPI e TIM

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2#14]
Referências:

TPI
[Andersin.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/286410/Andersin.pdf)
TIM
[a891451d001f9f6fdd2b9b4f896da567f0ab.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/286414/a891451d001f9f6fdd2b9b4f896da567f0ab.pdf)
Comparação entre TMM, TPI e TIM
[12-4-1-FPdef.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/286411/12-4-1-FPdef.pdf)

[TPI - 'Key Areas x Levels' Table](https://docs.google.com/a/cin.ufpe.br/spreadsheets/d/1pt3V87EqnANW4qnqY4ITMXhzJ-KzmnuxyxjkFYceRbo/edit?usp=sharing)

**Comment by JoaoGFarias** [comment]
@vsychen 

Acho que esses dois textos podem te ajudar:

O primeiro, principalmente, tem outro foco, mas detalha mais TPI e TIM.
Como diz a conclusão do segundo link, o principal (e também bem estruturado por se basear no CMMI) é o TMMI, mas detalhar o TPI e TIM é interessante para o artigo.

[MODELO DE MATURIDADE EM TESTES COM FOCO EM 
AMBIENTES DE TESTES HETEROGÊNEOS] (http://www.repositorio.ufpe.br/bitstream/handle/123456789/2711/arquivo6680_1.pdf?sequence=1&isAllowed=y )

[Modelos de Maturidade de Testes (slides)](https://www.google.com.br/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjw6oq3p4PNAhVCkJAKHelODjQQFgggMAA&url=http%3A%2F%2Fwww.cin.ufpe.br%2F~processos%2FTAES3%2Fslides-2008.2%2FModelos%2520de%2520Maturidade%2520de%2520Testes%2520-%2520Juliana%2520Mafra.ppt&usg=AFQjCNF94w55PxUZKUqTQDxlvbzLK5YrLg&sig2=9HlPpI9PhPS1ybvPT0MWvA&cad=rja)

**Comment by vsychen** [comment]
Termino esse resumo até sexta feira, no máximo.

**Comment by vsychen** [comment]
Muitos malz pelo atraso. Tinha terminado ontem a noite, mas dormi antes de upar e.e

[TPITIM-Resumo.pdf](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/files/300391/TPITIM-Resumo.pdf)

**Comment by JoaoGFarias** [comment]
@vsychen, tudo pode colocar isso em um markdown na [pasta do de referências do artigo](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/tree/master/artigo) para ficar mais fácil de editarmos?

Depois, pode fechar a issue.
