### ISSUE TITLE
[Artigo] Sumário

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2#15]
Criar e manter um arquivo markdown com o sumário do artigo

**Comment by JoaoGFarias** [comment]
Feito no commit https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/commit/fef7c8bcaa4b331ecd93395e7450f4af7dd131b1

@brilacerda queria teu feedback nisso. É só um rascunho, mas acho que cobre os pontos de mais alto nível.

**Comment by brilacerda** [comment]
@brunnorbc @vsychen @acff @JoaoGFarias  por ser um artigo eu acredito que o professor pode não gostar da estrutura, te explicarei por que e gostaria também que vocês opinassem.

Um artigo tem como objetivo "demonstrar, confirmar/desmentir, ilustrar, exemplificar, testar, comparar, recomendar etc. O começo, o meio e o fim do artigo devem estar claros para você antes de ele começar a ser escrito."

E aí no nosso caso, o que queremos fazer com o nosso artigo? Já temos alguma ideia clara disso? Alguém tem e quer compartilhar conosco para que possamos focar?

**Comment by brilacerda** [comment]
Eu sugiro fazermos uma crítica de por que realizar testes e os benefícios de TDD.
Acho mais simples, o que acham? fica mais resumido. Ou talvez fazer um comparativo entre TDD e TMMI. Acho mais bacana. Vamos decidir isso logoooooooo!!!!!

**Comment by brilacerda** [comment]
Ou um comparativo entre adaptive software development (ASD)

**Comment by JoaoGFarias** [comment]
> O começo, o meio e o fim do artigo devem estar claros para você antes de ele começar a ser escrito." E aí no nosso caso, o que queremos fazer com o nosso artigo? Já temos alguma ideia clara disso? Alguém tem e quer compartilhar conosco para que possamos focar?

O artigo é uma proposta de modelo de maturidade de testes ágeisl, A(Agile)TMM.
Como o professor falou quando tiramos o tema, temos que [explicar o que é teste de software em si](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/commit/fef7c8bcaa4b331ecd93395e7450f4af7dd131b1#diff-de386ee348e539cd38edbe2c35abde13R4); adicionalmente, vamos explicar [o que é o movimento ágil, especialmente para testes](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/commit/fef7c8bcaa4b331ecd93395e7450f4af7dd131b1#diff-de386ee348e539cd38edbe2c35abde13R5) e, para finalizar a contextualização, explicar [dar um overview dos modelos de maturidade de testes existentes](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/commit/fef7c8bcaa4b331ecd93395e7450f4af7dd131b1#diff-de386ee348e539cd38edbe2c35abde13R9).

Depois que os termos e conceitos estão bem estelecidos, é fácil [entender os pontos importantes para análise da maturidade de testes ágeis](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/commit/fef7c8bcaa4b331ecd93395e7450f4af7dd131b1#diff-de386ee348e539cd38edbe2c35abde13R17).
A parte de [avaliação do ATMMI](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/commit/fef7c8bcaa4b331ecd93395e7450f4af7dd131b1#diff-de386ee348e539cd38edbe2c35abde13R19) é mais por completude; não é um must para esse artigo, eu acho.

Dúvidas? Sentimentos?

**Comment by JoaoGFarias** [comment]
>Eu sugiro fazermos uma crítica de por que realizar testes e os benefícios de TDD.

O tema foi Modelos de Maturidade de Testes; metodologias de testes e desenvolvimento são outro assunto. O que com certeza vai entrar é a exemplificação de metodologias para práticas e objetivos do modelo (Apenas exemplos, pois devemos dizer _o que fazer_ não _como fazer_ ). 

Por exemplo: 

* [No nível 3](http://www.tctgroup.com/tctcomputing/consulting/Five-Levels-of-TMMi_large.gif), podemos dizer que devem existir testes automáticos de nível de integração; e no [4](http://www.tctgroup.com/tctcomputing/consulting/Five-Levels-of-TMMi_large.gif) deve-se usar medidas de cobertura de código para análise de qualidade.

* Podemos dizer que no nível 4 deve-se ter partes testes de aceitação realizados por automação; no nível 5, testes de aceitação automáticos devem dirigir o desenvolvimento.


>Ou talvez fazer um comparativo entre TDD e TMMI. Ou um comparativo entre adaptive software development (ASD)

Laranjas e peras, não? TDD e ASD são metodologias de desenvolvimento e TMMI é um modelo de avaliação de maturidade de testes.

**Comment by JoaoGFarias** [comment]
Mais alguma consideração @brilacerda ?
