### ISSUE TITLE
[BPMN] Estudar seção de Monitoramento e Controle

### ISSUE THREAD

**Issue by JoaoGFarias** [JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2#4]
Leitura das páginas 271 à 281 do [CMMI for Dev](https://github.com/JoaoGFarias/Qualidade-de-Software_CIn-UFPE_2016.1_Equipe-2/blob/master/modelagem_bpmn/referencias/cmmi_for_dev.pdf)

Assignees:
@brilacerda 
@brunnorbc 
@vsychen 
@acff 
@JoaoGFarias

**Comment by vsychen** [comment]
João, essa parte e PP, não sei se a gente precisa realmente estudar. Acho que só ler por cima já basta, porque esses 2 foram designados pra 2 outros grupos

**Comment by JoaoGFarias** [comment]
@vsychen, essa é uma área relacionada a CM (Vide CMMI-Dev).
Essa issue e #5 serve para termos ciência dessas áreas.
